name: Mercury
softdepend: [ViaVersion, PlaceholderAPI, Vault, DiscordSRV, Vulcan, LunarClient-API, BadlionClientTimerAPI]
description: ${project.parent.description}
main: ${project.mainClass}
version: ${project.version}
website: ${project.parent.url}
